version: "3.8"

services:
  flask_app:
    container_name: flask_app
    build: .
    ports:
      - 8080:5000
    volumes:
      - .:/app
    restart: unless-stopped
    command: ['python', 'app.py']
